name: CI

on: [push]

jobs:
  main:
    name: CI
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: 3.9
            toxenv: py
          - os: ubuntu-latest
            python: "3.10"
            toxenv: py
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - run: python -m pip install --upgrade setuptools pip tox==4.4.4 virtualenv
      - run: tox -e ${{ matrix.toxenv }}
